# Generated by Django 4.2.10 on 2024-02-21 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='factures',
            fields=[
                ('facture_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type_facture', models.CharField(max_length=50)),
                ('emetteur', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('mail_emetteur', models.CharField(max_length=50)),
                ('date_emission', models.CharField(max_length=50)),
                ('date_echeance', models.CharField(max_length=50)),
                ('conditions', models.CharField(max_length=50)),
                ('total', models.FloatField()),
                ('facture_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='MyImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.FloatField()),
                ('somme', models.FloatField()),
                ('codeProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.factures')),
            ],
        ),
    ]
